#
# OrangeFox Board Config for Realme C53 (RMX3760 / RE58C2)
#

# Device info
FOX_AB_DEVICE := 1
FOX_VIRTUAL_AB_DEVICE := 1
FOX_VENDOR_BOOT_RECOVERY := 1
FOX_VANILLA_BUILD := 1
# Maintainer
OF_MAINTAINER := cooked71
FOX_MAINTAINER_PATCH_VERSION := 1

# Screen (720x1600 HD+)
OF_SCREEN_H := 1600
OF_SCREEN_W := 720
OF_STATUS_H := 72
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 2
OF_ALLOW_DISABLE_NAVBAR := 0
OF_HIDE_NOTCH := 1

# Encryption - CRITICAL for Android 15 FBE
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_USE_FSCRYPT_POLICY := 2
BOARD_USES_METADATA_PARTITION := true
OF_FBE_METADATA_MOUNT_POINT := /metadata
OF_SKIP_FBE_DECRYPTION := false
OF_NO_RELOAD_AFTER_DECRYPTION := true
OF_USE_LOCKSCREEN_BUTTON := true
OF_SUPPORT_VBMETA_AVB := true
OF_PATCH_AVB20 := true
OF_DONT_PATCH_ENCRYPTED_DEVICE := true
OF_FIX_DECRYPTION_ON_DATA_MEDIA := true
OF_DEFAULT_KEYMASTER_VERSION := 4.0
OF_SKIP_DECRYPTED_ADOPTED_STORAGE := true

# Fstab / mount handling
OF_IGNORE_LOGICAL_MOUNT_ERRORS := true
OF_LOOP_DEVICE_ERRORS_TO_LOG := true
OF_FORCE_PREBUILT_KERNEL := true
OF_USE_TWRP_SAR_DETECT := true
OF_NO_TREBLE_COMPATIBILITY_CHECK := true
OF_CHECK_OVERWRITE_ATTRIBUTES := true

# Non-Xiaomi / MIUI
OF_DISABLE_MIUI_SPECIFIC_FEATURES := true
OF_NO_MIUI_PATCH_WARNING := true
OF_NO_ADDITIONAL_MIUI_PROPS_CHECK := true
OF_DISABLE_MIUI_OTA_BY_DEFAULT := true
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := false

# Splash / theme / brightness
OF_NO_SPLASH_CHANGE := true
OF_TWRP_COMPATIBILITY_MODE := true
TW_MAX_BRIGHTNESS := 2048
TW_DEFAULT_BRIGHTNESS := 1400

# Tools
OF_USE_MAGISKBOOT := true
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := true
OF_ENABLE_LPTOOLS := true
OF_ENABLE_ALL_PARTITION_TOOLS := true

# KernelSU support (for future)
FOX_ENABLE_KERNELSU_SUPPORT := false
FOX_ENABLE_KERNELSU_NEXT_SUPPORT := false

# Vibrator path (from stock)
OF_VIB_PATH := /sys/class/timed_output/vibrator/enable

# Misc
OF_QUICK_BACKUP_LIST := /boot;/data;/vendor_boot;
OF_DEFAULT_TIMEZONE := WIB-7
OF_USE_LZMA_COMPRESSION := 0
OF_USE_LZ4_COMPRESSION := 1
